api_platform:
  title: 'PetsCare Users API'
  description: 'API pour la gestion des utilisateurs PetsCare'
  version: 1.0.0
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'
      - '%kernel.project_dir%/src/Controller'
  defaults:
    stateless: true
    cache_headers:
      vary: ['Content-Type', 'Authorization', 'Origin']
